# -*- coding: utf-8 -*-
"""SBERT_Cos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ET9NIAndMXv4j5uOheM1bUWBNIIaB3O0
"""

from fastapi import FastAPI, Request
from sentence_transformers import SentenceTransformer, util
import torch

app = FastAPI()

# モデル読み込み（初回のみ少し時間がかかる）
model = SentenceTransformer('all-MiniLM-L6-v2')

@app.post("/similarity")
async def similarity(request: Request):
    data = await request.json()
    s1 = data["text1"]
    s2 = data["text2"]

    e1 = model.encode(s1, convert_to_tensor=True)
    e2 = model.encode(s2, convert_to_tensor=True)

    score = util.pytorch_cos_sim(e1, e2).item()
    return {"similarity": score}